export default {
  Images: {
    placeholderRestaurant: require('../../assets/images/restaurant_home.jpg'),
    placeholderFood: require('../../assets/images/placeholder-food.png'),
    starters: require('../../assets/images/chinese.png'),
    'Main course': require('../../assets/images/south-indian.png'),
    Drinks: require('../../assets/images/beverages.png'),
    'north-india': require('../../assets/images/north-indian.png'),
    'north-indian': require('../../assets/images/north-indian.png'),
    biryanis: require('../../assets/images/biryani.png'),
    Dessert: require('../../assets/images/desserts.png'),
    'ice-creams': require('../../assets/images/ice-creams.png'),
    mexican: require('../../assets/images/mexican.png'),
    pizza: require('../../assets/images/pizza.png'),
    foodBg: require('../../assets/images/foodBg.png'),
    banana: require('../../assets/images/banana.png'),
    paymentComplete: require('../../assets/images/check.png'),
    paymentFailed: require('../../assets/images/cross.png'),
    'The Langham': require('../../assets/images/restaurant_home.jpg'),
  },
};
